language: d
sudo: true

d:
 - dmd-2.066.1
 - dmd-2.066.0

install:
  - sudo apt-get install libenet-dev

script:
  - dub test gfm:core
  - dub test gfm:math
  - dub test gfm:net
  - dub test gfm:enet
  - dub test gfm:sdl2
  - dub test gfm:opengl
  - dub test gfm:assimp
  - dub test gfm:freeimage
  - dub test gfm:image
  - dub test gfm:logger
